# fly.toml app configuration file generated for se-nnn-carrental-be on 2025-03-31T20:22:22+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'se-nnn-carrental-be'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
